#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

path=(
   /home/thor/.cabal/bin
   $(ruby -e "print Gem.user_dir")/bin
   /home/thor/develop/geoscript-groovy-1.9.0/bin
   $path
)

export PATH

export EDITOR=/usr/bin/vim

